version: '3'

services:
    client:
        build: client
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app/
        depends_on:
            - server
        links:
            - server
    server:
        build: server
        volumes:
            - ./server:/app/
